name: Jupyter Server

on:
  workflow_dispatch:
    inputs:
      lastVersion:
        description: "Last Version"
        required: true
        default: "1.0.10"

jobs:
  job1:
    name: Testing this job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Ruby
      uses: actions/setup-ruby@v1
    - name: Install github changelog generator
      run: |
        gem install github_changelog_generator
    - name: Generate ChangeLog
      run: |
        github_changelog_generator -u jupyter-server \
        -p jupyter_server \
        --token ${{ secrets.GITHUB_TOKEN }} \
        --no-issues \
        --since-tag ${{ github.event.inputs.lastVersion }} \
        --output changelog.md
    - name: Get current date
      id: date
      run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Upload Changelog to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.lastVersion }}-${{ env.current_date }}
        path: changelog.md
